### PR TITLE
Show docs as docs, not as sources

### PR DESCRIPTION
**Pull request by AlexeyRaga**
## Changes

`HIE` provides very useful links to documentation and source in a hover popup. Unfortunately, `VSCode` now opens these links in its tabs as HTML source, not as readable documentation.
The issue was tracked in https://github.com/Microsoft/vscode/issues/36452 with the resolution that this behaviour is expected.

This PR fixes the issue by opening haddock docs and sources in a human-readable form:

show-docs

### CODE REVIEW

**Comment by alanz** [comment]
Thanks

**Comment by YSMull** [comment]
this feature is not work.
ref:https://github.com/Microsoft/vscode/issues/36452

**Comment by Tehnix** [comment]
Hmm, it seems this broke after updating the dependency on `vscode-languageclient` from 3.5 to 4.0.1.

**Comment by Tehnix** [comment]
I've reverted this, since multi-root and everything still seems to be working under 3.5.0. When version 0.0.14 is on the store (building atm), you can get the fix in that version.

**Pull request merged**
