### PR TITLE
Show type on hover

### PR DESCRIPTION
**Pull request by halhenke**
Added an option to automatically show the type for a selected expression feature when the user hovers over an expression (appears at the bottom of the popover after currently displayed information).

show-type

Also added options for how to display the same information when using the `show type` command menu & moved the configuration setting about showing trace information into the proper scope (not sure if you want to keep it?)

### CODE REVIEW

**Comment by AlexeyRaga** [comment]
👍 That's awesome! //cc @alanz in case of GH notifications problem

**Comment by alanz** [comment]
Published as v 0.0.7, thanks

**Comment by alanz** [comment]
@halhenke FYI see https://github.com/Microsoft/language-server-protocol/issues/377

**Comment by halhenke** [comment]
@alanz Nice 👍

**Pull request merged**
