### PR TITLE
Implement insert type command

### PR DESCRIPTION
**Pull request by AlexeyRaga**
## Changes

- Insert type for top-level and inlined expressions

**Note** This PR is implemented against the `cleanup` branch of the `ide-engine`

### CODE REVIEW

**Comment by wz1000** [comment]
Great job! This is really cool.

However, I can think of one bug in this implementation (if I am reading the code correctly). If there is no newline after a `let` or `where`, it will insert the type as though it is an expression.

```haskell
  where foo = ...
```
calling the type insertion function would turn it into

```haskell
  where (foo = ... :: T)
```

Since we don't need to support type insertion when the file doesn't compile, I think the best way to implement this would use the AST we get from GHC, possibly in the form of a HaRe refactoring. Another bonus of this method would be that we won't need complex logic on the editor plugin side, which is the main goal of HIE.

**Comment by AlexeyRaga** [comment]
I agree that going through Hare/AST would be a better solution :)

**Comment by wz1000** [comment]
@AlexeyRaga How much effort would fixing the bug I pointed out take? If the solution could be complex/hacky, we will merge this 'as is' after the cleanup branch lands(soon^TM), because we plan on moving the functionality into hie/hare whenever we have the time.

**Comment by AlexeyRaga** [comment]
Not that hard, here is a fixed version:

inserttypefix

However, there are still edge cases, mostly around record fields, see two examples below.
I was curious about how other Haskell plugins deal with these issues and I have checked `Haskero` for VSCode and `ghc-mod` extension for Atom and found that they don't handle these cases too.
Atom's `ghc-mod` plugin does something very similar to what I do, and `Haskero` does something even weirder.

Anyway, here are my issues:
inserttypewrong

I currently don't know how to detect that I am dealing with the record fields and treat them separately somehow. 

and also this one:

inserttypewrong2

If you have any ideas about how it can be fixed/hacked I could try implementing it!

Anyway, feel free to take it or not, I am mostly doing it for myself because inserting type is one of the features I use a lot, and I really want to use HIE because of its speed :)

P.S. I am very interested to see how it can be done at HIE side through AST. One reason I didn't look at that side is that with updating AST directly I don't know how to preserve user's preferred formatting.

**Comment by AlexeyRaga** [comment]
Ops, one more thing, will check/fix it now.

**Comment by AlexeyRaga** [comment]
Forgot to test with `let`. Checked, and it worked (`Haskero` didn't ;))

**Comment by alanz** [comment]
FYI, ghc-exactprint exists to be able to modify the GHC AST and preserve formatting

**Comment by AlexeyRaga** [comment]
Wow, interesting, thanks for the information!

**Comment by alanz** [comment]
It is also used as the basis for [brittany](https://github.com/lspitzner/brittany) a code formatter, also exposed in hie

**Pull request merged**
