### PR TITLE
Add option to configure the number of shake threads

### PR DESCRIPTION
**Pull request by bubba**
Only on ghcide and haskell-language-server

https://github.com/digital-asset/ghcide/commit/39605333c34039241768a1809024c739df3fb2bd

### CODE REVIEW

**Comment by jneira** [comment]
Uhmm, this could be useful, but it seems to me that it will be a thing mainly oriented to ghcide/hls developers.
Not sure i it worths add a specific option visible to everybody, as you can make a wrapper for example and pass the argument there.

**Comment by bubba** [comment]
True. We could alternatively just always pass `-j 0`, but I guess this depends on whether or not we want multithreading to be the default. Does anyone know if it’s considered experimental or stable?

**Comment by jneira** [comment]
Well, maybe a slightly more generic name could make it more user oriented: `languageServerHaskell.numThreads` or a boolean `multithreading`. 
Is not `-j 0` already the default value?

**Comment by bubba** [comment]
You might be right. We don't pass -j 0 by default but I'll need to check if leaving out `-j` is actually multithreaded – I had just assumed it was the same behaviour as make

**Comment by bubba** [comment]
After a bit of poking, it does look like ghcide sets the number of shake threads to 0 by default, which should mean it is by default multithreaded. But on haskell-language-server, it defaults to 1, so single threaded. I think this is probably more of an oversight in hls, I will address that there

**Pull request closed without merging**
